AcmMvcApp/Controllers/ContentDispController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using AcmMvcApp.Models;

namespace AcmMvcApp.Controllers
{
    public class ContentDispController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Content/

        public ActionResult Index()
        {
            return View(db.Contents.ToList());
        }

        //
        // GET: /Content/Details/5

        public ActionResult Details(int id = 0)
        {
            ContentDisp content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        //
        // GET: /Content/Create

        public ActionResult Create()
        {

            ContentViewModel cvm = new ContentViewModel();
            
            return View(cvm);
        }

        //
        // POST: /Content/Create

        [HttpPost]
        public ActionResult Create(ContentViewModel contentVm)
        {
            if (ModelState.IsValid)
            {

                string fileName = "";

                // локальная заливка файла в Temp_content
                if (contentVm.file != null && contentVm.file.ContentLength > 0)
                {
                    fileName = Path.GetFileName(contentVm.file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Temp_content/"), fileName);
                    contentVm.file.SaveAs(path);
                }

                db.Contents.Add(contentVm.content);
                db.SaveChanges();


                return RedirectToAction("Index");
            }

            return View(contentVm.content);
        }

        //
        // GET: /Content/Edit/5

        public ActionResult Edit(int id = 0)
        {
            ContentDisp content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            ContentViewModel cvm = new ContentViewModel();

            cvm.content = content;

            return View(cvm);
        }

        //
        // POST: /Content/Edit/5

        [HttpPost]
        public ActionResult Edit(ContentViewModel contentVm)
        {
            if (ModelState.IsValid)
            {

                string fileName = "";

                // локальная заливка файла в Temp_content
                if (contentVm.file != null && contentVm.file.ContentLength > 0)
                {
                    fileName = Path.GetFileName(contentVm.file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Temp_content/"), fileName);
                    contentVm.file.SaveAs(path);
                }

                if (contentVm.file != null && contentVm.file.ContentLength > 0)
                {
                    int indexOfDot = fileName.IndexOf('.');
                    contentVm.content.name = fileName.Substring(0, indexOfDot);
                    contentVm.content.extension = fileName.Substring(indexOfDot, fileName.Length - indexOfDot);
                }

                db.Entry(contentVm.content).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contentVm.content);
        }

        //
        // GET: /Content/Delete/5

        public ActionResult Delete(int id = 0)
        {
            ContentDisp content = db.Contents.Find(id);
            if (content == null)
            {
                return HttpNotFound();
            }
            return View(content);
        }

        //
        // POST: /Content/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            ContentDisp content = db.Contents.Find(id);
            db.Contents.Remove(content);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }

}

AcmMvcApp/Views/ContentDisp/Create.cshtml
@model AcmMvcApp.Models.ContentViewModel

@{
    ViewBag.Title = "Загрузка контента";
}

@*This is for jquery*@
<script src="../Scripts/jquery-1.7.2.js" type="text/javascript"></script>
@*This is for jquery UI, for Calender control*@
<script src="../Scripts/jquery-ui-1.8.20.js" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            var indexOfDot = fileName.indexOf('.');

            $("#content_name").val(fileName.substring(0, indexOfDot));
            $("#content_extension").val(fileName.substring(indexOfDot, fileName.length));
        });
    });

</script>

<h2>Загрузка контента</h2>

@using (Html.BeginForm("Create", "ContentDisp", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Content</legend>

        <div class="editor-label">
            <input type="file" name="file" id="file" required accept=".jpg"/>
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.content.name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.content.name)
            @Html.ValidationMessageFor(model => model.content.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.content.extension)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.content.extension)
            @Html.ValidationMessageFor(model => model.content.extension)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.content.duration)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content.duration)
            @Html.ValidationMessageFor(model => model.content.duration)
        </div>

        <p>
            <input type="submit" value="Загрузить" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Назад, к контенту", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AcmMvcApp/Views/ContentDisp/Delete.cshtml
@model AcmMvcApp.Models.ContentDisp

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Content</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.extension)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.extension)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.duration)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.duration)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

AcmMvcApp/Views/ContentDisp/Details.cshtml
@model AcmMvcApp.Models.ContentDisp

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Content</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.extension)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.extension)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.duration)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.duration)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AcmMvcApp/Views/ContentDisp/Edit.cshtml
@model AcmMvcApp.Models.ContentViewModel

@{
    ViewBag.Title = "Edit";
}

@*This is for jquery*@
<script src="../../Scripts/jquery-1.7.2.js" type="text/javascript"></script>
@*This is for jquery UI, for Calender control*@
<script src="../../Scripts/jquery-ui-1.8.20.js" type="text/javascript"></script>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $('input[type="file"]').change(function (e) {
            var fileName = e.target.files[0].name;
            var indexOfDot = fileName.indexOf('.');

            $("#content_name").val(fileName.substring(0, indexOfDot));
            $("#content_extension").val(fileName.substring(indexOfDot, fileName.length));
        });
    });

</script>

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "ContentDisp", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Content</legend>

        @Html.HiddenFor(model => model.content.Id)

        <div class="editor-label">
            <input type="file" name="file" id="file" required accept=".jpg" />
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.content.name)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.content.name)
            @Html.ValidationMessageFor(model => model.content.name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.content.extension)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.content.extension)
            @Html.ValidationMessageFor(model => model.content.extension)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.content.duration)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.content.duration)
            @Html.ValidationMessageFor(model => model.content.duration)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AcmMvcApp/Views/ContentDisp/Index.cshtml
@model IEnumerable<AcmMvcApp.Models.ContentDisp>

@{
    ViewBag.Title = "Index";
}

<h2>Контент</h2>

<p>
    @Html.ActionLink("Загрузить", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.extension)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.extension)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.duration)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>